---
- name: Install httpd server on CentOS
  yum: name=httpd state=present

- name: Start httpd
  service: name=httpd state=started enabled=yes
  when: ansible_distribution == "CentOS"

- name: Update httpd default config
  copy: src=httpd.conf dest=/etc/httpd/conf/
  notify:
    - Reload httpd configuration

- name: Flush handlers
  meta: flush_handlers

- name: Copy the index files
  template:
    dest: /var/www/html/index.html
    src: index.html.j2
