- hosts: two
  gather_facts: true
  vars:
    my_name: Tyler
  vars_prompt:
    - name: username
      prompt: Enter a username
      private: no
  tasks:
    - yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"


    - name: Print username
      debug:
        msg: 'Hello {{username}}'

    - name: Create user
      user:
        name: username

    - name: Create file
      file:
        path: "/home/ec2-user/{{username}}.txt"
        state: touch

    - debug:
        var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Set hostname
      hostname: 
        name: username

    - name: Print hostname
      debug:
        msg: 'Host: {{ansible_hostname}}'