- hosts: two
  gather_facts: true
  vars:
    my_name: Tyler
  vars_prompt:
    - name: username
      prompt: Enter a username
      private: no
  tasks:
    - yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"


    - name: Print username
      debug:
        msg: 'Hello {{username}}'

    - name: Create user
      user:
        name: {{username}}


