- hosts: two
  gather_facts: true
  vars:
    my_name: Tyler
  tasks:
    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "CentOS"

    - apt:
        pkg: apache2
        state: installed
      when: ansible_distribution == "Ubuntu"


