- hosts: two
  gather_facts: true
  vars:
    my_name: Tyler
  tasks:
    - yum:
        name: httpd
        state: removed
      when: ansible_distribution == "CentOS"

    - apt:
        name: apache2
        state: absent
      when: ansible_distribution == "Ubuntu"


