---
- hosts: webserver
  gather_facts: false
  tasks:
  - name: Install packages
    yum:
      name: "{{item}}"
      state: removed
    with_items:
    - mlocate
    - strace
    - java-1.8.0-openjdk
    - php

  - name: Create directories
    file:
      path: "/home/lab4/{{item}}"
      state: absent
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate