---
- hosts: webservers  # Host or Group of Selections
  tasks:
  - name: Install httpd # Naming the task for debug purpose
    yum: name=httpd state=present  # Using module ( doing the task )

- hosts: dbservers  # Host or Group of Selections
  tasks:
  - name: Install mysql server # Naming the task for debug purpose
    yum: name=mysql-server state=present  # Using module ( doing the task )