---
#- name: Replace port
#  template:
#    src: vars.yml.j2
#    dest: tom_install/vars/main.yml

- name: Find extra-vars
  debug:
    var: result


- name: Installing Tomcat on Web Server
  hosts: webserver
  become: no
  gather_facts: no
  roles:
    - update_repos
    - tom_java
    - tom_install
  
- name: Installing MySQL Server on Database Server
  hosts: dbserver
  become: no
  gather_facts: no
  roles:
    - db
